name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          allow-prereleases: true
      - name: Install Pre-Commit
        run: python -m pip install pre-commit && pre-commit install
      - name: Load cached Pre-Commit Dependencies
        id: cached-pre-commit-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Execute Pre-Commit
        run: pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
    uses: ./.github/workflows/test.yaml
    with:
      python-version: ${{ matrix.python-version }}
      coverage: ${{ matrix.python-version == '3.11' }}

  audit:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
    uses: ./.github/workflows/audit.yaml
    with:
      python-version: ${{ matrix.python-version }}

  codecov:
    needs: test
    if: github.event.pull_request.head.repo.fork == false && github.repository_owner == 'JacobCoffee'
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  sonar:
    needs: test
    if: github.event.pull_request.head.repo.fork == false && github.repository_owner == 'JacobCoffee'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-xml
      - name: Fix coverage file for sonarcloud
        run: sed -i "s/home\/runner\/work\/litestar-template\/app/github\/workspace/g" coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# snyk seems to not support PDM?
#  snyk:
#    needs:
#      - test
#      - validate
#    if: github.event.pull_request.head.repo.fork == false && github.repository_owner == 'JacobCoffee'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Run Snyk Monitor
#        if: ${{ github.ref == 'refs/heads/main' }}
#        uses: snyk/actions/python@master
#        with:
#          command: monitor
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#      - name: Run Snyk Test
#        if: ${{ github.ref != 'refs/heads/main' }}
#        uses: snyk/actions/python@master
#        with:
#          command: test
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  changelog:
    needs:
      - test
      - validate
    if: github.event.pull_request.head.repo.fork == false && github.repository_owner == 'JacobCoffee'
    runs-on: ubuntu-latest
    steps:
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: changelog.rst
